### ISSUE TITLE
Task Id : attempt_1523813863666_0001_m_003170_0, Status : FAILED

### ISSUE THREAD

**Issue by iShiBin** [iShiBin/access-log-analyzer#5]
The very last map job failed for 3 times and then lead to the entire MR job failure.
```
2018-04-15 18:00:16,136 INFO org.apache.hadoop.mapreduce.Job (main):  map 50% reduce 12%
2018-04-15 18:00:20,151 INFO org.apache.hadoop.mapreduce.Job (main):  map 50% reduce 13%
2018-04-15 18:00:44,248 INFO org.apache.hadoop.mapreduce.Job (main):  map 51% reduce 13%
2018-04-15 18:01:10,352 INFO org.apache.hadoop.mapreduce.Job (main):  map 51% reduce 14%
2018-04-15 18:01:16,373 INFO org.apache.hadoop.mapreduce.Job (main):  map 52% reduce 14%
2018-04-15 18:01:41,478 INFO org.apache.hadoop.mapreduce.Job (main):  map 53% reduce 14%
2018-04-15 18:02:12,597 INFO org.apache.hadoop.mapreduce.Job (main):  map 54% reduce 14%
2018-04-15 18:02:41,711 INFO org.apache.hadoop.mapreduce.Job (main):  map 55% reduce 14%
2018-04-15 18:03:02,790 INFO org.apache.hadoop.mapreduce.Job (main):  map 55% reduce 15%
2018-04-15 18:03:07,808 INFO org.apache.hadoop.mapreduce.Job (main):  map 56% reduce 15%
2018-04-15 18:03:40,940 INFO org.apache.hadoop.mapreduce.Job (main):  map 57% reduce 15%
2018-04-15 18:04:07,045 INFO org.apache.hadoop.mapreduce.Job (main):  map 58% reduce 15%
2018-04-15 18:04:33,150 INFO org.apache.hadoop.mapreduce.Job (main):  map 59% reduce 15%
2018-04-15 18:04:52,227 INFO org.apache.hadoop.mapreduce.Job (main):  map 59% reduce 16%
2018-04-15 18:05:06,286 INFO org.apache.hadoop.mapreduce.Job (main):  map 60% reduce 16%
2018-04-15 18:05:33,393 INFO org.apache.hadoop.mapreduce.Job (main):  map 61% reduce 16%
2018-04-15 18:05:56,485 INFO org.apache.hadoop.mapreduce.Job (main):  map 62% reduce 16%
2018-04-15 18:06:31,616 INFO org.apache.hadoop.mapreduce.Job (main):  map 63% reduce 16%
2018-04-15 18:06:39,643 INFO org.apache.hadoop.mapreduce.Job (main):  map 63% reduce 17%
2018-04-15 18:06:59,717 INFO org.apache.hadoop.mapreduce.Job (main):  map 64% reduce 17%
2018-04-15 18:07:26,812 INFO org.apache.hadoop.mapreduce.Job (main):  map 65% reduce 17%
2018-04-15 18:07:55,914 INFO org.apache.hadoop.mapreduce.Job (main):  map 66% reduce 17%
2018-04-15 18:08:25,012 INFO org.apache.hadoop.mapreduce.Job (main):  map 67% reduce 17%
2018-04-15 18:08:30,028 INFO org.apache.hadoop.mapreduce.Job (main):  map 67% reduce 18%
2018-04-15 18:08:54,122 INFO org.apache.hadoop.mapreduce.Job (main):  map 68% reduce 18%
2018-04-15 18:09:22,215 INFO org.apache.hadoop.mapreduce.Job (main):  map 69% reduce 18%
2018-04-15 18:09:52,349 INFO org.apache.hadoop.mapreduce.Job (main):  map 70% reduce 18%
2018-04-15 18:10:19,445 INFO org.apache.hadoop.mapreduce.Job (main):  map 70% reduce 19%
2018-04-15 18:10:21,452 INFO org.apache.hadoop.mapreduce.Job (main):  map 71% reduce 19%
2018-04-15 18:10:49,554 INFO org.apache.hadoop.mapreduce.Job (main):  map 72% reduce 19%
2018-04-15 18:11:17,659 INFO org.apache.hadoop.mapreduce.Job (main):  map 73% reduce 19%
2018-04-15 18:11:47,750 INFO org.apache.hadoop.mapreduce.Job (main):  map 74% reduce 19%
2018-04-15 18:12:07,811 INFO org.apache.hadoop.mapreduce.Job (main):  map 74% reduce 20%
2018-04-15 18:12:14,831 INFO org.apache.hadoop.mapreduce.Job (main):  map 75% reduce 20%
2018-04-15 18:12:43,996 INFO org.apache.hadoop.mapreduce.Job (main):  map 76% reduce 20%
2018-04-15 18:13:11,084 INFO org.apache.hadoop.mapreduce.Job (main):  map 77% reduce 20%
2018-04-15 18:13:41,172 INFO org.apache.hadoop.mapreduce.Job (main):  map 78% reduce 20%
2018-04-15 18:13:57,219 INFO org.apache.hadoop.mapreduce.Job (main):  map 78% reduce 21%
2018-04-15 18:14:07,249 INFO org.apache.hadoop.mapreduce.Job (main):  map 79% reduce 21%
2018-04-15 18:14:37,346 INFO org.apache.hadoop.mapreduce.Job (main):  map 80% reduce 21%
2018-04-15 18:15:05,431 INFO org.apache.hadoop.mapreduce.Job (main):  map 81% reduce 21%
2018-04-15 18:15:33,516 INFO org.apache.hadoop.mapreduce.Job (main):  map 82% reduce 21%
2018-04-15 18:15:45,550 INFO org.apache.hadoop.mapreduce.Job (main):  map 82% reduce 22%
2018-04-15 18:16:02,600 INFO org.apache.hadoop.mapreduce.Job (main):  map 83% reduce 22%
2018-04-15 18:16:30,683 INFO org.apache.hadoop.mapreduce.Job (main):  map 84% reduce 22%
2018-04-15 18:16:58,775 INFO org.apache.hadoop.mapreduce.Job (main):  map 85% reduce 22%
2018-04-15 18:17:28,868 INFO org.apache.hadoop.mapreduce.Job (main):  map 86% reduce 22%
2018-04-15 18:17:33,882 INFO org.apache.hadoop.mapreduce.Job (main):  map 86% reduce 23%
2018-04-15 18:17:55,950 INFO org.apache.hadoop.mapreduce.Job (main):  map 87% reduce 23%
2018-04-15 18:18:24,032 INFO org.apache.hadoop.mapreduce.Job (main):  map 88% reduce 23%
2018-04-15 18:18:52,109 INFO org.apache.hadoop.mapreduce.Job (main):  map 89% reduce 23%
2018-04-15 18:19:22,190 INFO org.apache.hadoop.mapreduce.Job (main):  map 90% reduce 24%
2018-04-15 18:19:51,272 INFO org.apache.hadoop.mapreduce.Job (main):  map 91% reduce 24%
2018-04-15 18:20:17,346 INFO org.apache.hadoop.mapreduce.Job (main):  map 92% reduce 24%
2018-04-15 18:20:48,445 INFO org.apache.hadoop.mapreduce.Job (main):  map 93% reduce 24%
2018-04-15 18:21:08,501 INFO org.apache.hadoop.mapreduce.Job (main):  map 93% reduce 25%
2018-04-15 18:21:17,524 INFO org.apache.hadoop.mapreduce.Job (main):  map 94% reduce 25%
2018-04-15 18:21:47,608 INFO org.apache.hadoop.mapreduce.Job (main):  map 95% reduce 25%
2018-04-15 18:22:16,688 INFO org.apache.hadoop.mapreduce.Job (main):  map 96% reduce 25%
2018-04-15 18:22:46,768 INFO org.apache.hadoop.mapreduce.Job (main):  map 97% reduce 25%
2018-04-15 18:23:03,823 INFO org.apache.hadoop.mapreduce.Job (main):  map 97% reduce 26%
2018-04-15 18:23:12,849 INFO org.apache.hadoop.mapreduce.Job (main):  map 98% reduce 26%
2018-04-15 18:23:40,923 INFO org.apache.hadoop.mapreduce.Job (main):  map 99% reduce 26%
2018-04-15 18:23:59,971 INFO org.apache.hadoop.mapreduce.Job (main): Task Id : attempt_1523813863666_0001_m_003170_0, Status : FAILED
2018-04-15 18:24:00,994 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 26%
2018-04-15 18:24:09,016 INFO org.apache.hadoop.mapreduce.Job (main): Task Id : attempt_1523813863666_0001_m_003170_1, Status : FAILED
2018-04-15 18:24:13,024 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 28%
2018-04-15 18:24:14,026 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 30%
2018-04-15 18:24:15,029 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 32%
2018-04-15 18:24:17,034 INFO org.apache.hadoop.mapreduce.Job (main): Task Id : attempt_1523813863666_0001_m_003170_2, Status : FAILED
2018-04-15 18:24:19,038 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 33%
2018-04-15 18:24:25,056 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 16%
2018-04-15 18:24:26,059 INFO org.apache.hadoop.mapreduce.Job (main):  map 100% reduce 100%
2018-04-15 18:24:26,063 INFO org.apache.hadoop.mapreduce.Job (main): Job job_1523813863666_0001 failed with state FAILED due to: Task failed task_1523813863666_0001_m_003170
Job failed as tasks failed. failedMaps:1 failedReduces:0

2018-04-15 18:24:26,323 INFO org.apache.hadoop.mapreduce.Job (main): Counters: 46
	File System Counters
		FILE: Number of bytes read=0
		FILE: Number of bytes written=536630038
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=440491
		HDFS: Number of bytes written=0
		HDFS: Number of read operations=3169
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=0
		S3: Number of bytes read=210247603045
		S3: Number of bytes written=0
		S3: Number of read operations=0
		S3: Number of large read operations=0
		S3: Number of write operations=0
	Job Counters 
		Failed map tasks=4
		Killed map tasks=4
		Killed reduce tasks=19
		Launched map tasks=3176
		Launched reduce tasks=19
		Other local map tasks=3
		Data-local map tasks=3173
		Total time spent by all maps in occupied slots (ms)=4731844464
		Total time spent by all reduces in occupied slots (ms)=2936581440
		Total time spent by all map tasks (ms)=98580093
		Total time spent by all reduce tasks (ms)=30589390
		Total vcore-milliseconds taken by all map tasks=98580093
		Total vcore-milliseconds taken by all reduce tasks=30589390
		Total megabyte-milliseconds taken by all map tasks=151419022848
		Total megabyte-milliseconds taken by all reduce tasks=93970606080
	Map-Reduce Framework
		Map input records=533873008
		Map output records=533873008
		Map output bytes=8008095120
		Map output materialized bytes=1019444
		Input split bytes=440491
		Combine input records=533873008
		Combine output records=3299
		Spilled Records=3299
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=1984288
		CPU time spent (ms)=30649380
		Physical memory (bytes) snapshot=2156431638528
		Virtual memory (bytes) snapshot=10474847567872
		Total committed heap usage (bytes)=1949629939712
	File Input Format Counters 
		Bytes Read=210247603045
```

**Comment by iShiBin** [comment]
Found this in the job history:

```
2018-04-15 18:23:59,590 INFO [main] com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem: Opening 's3://cloudacl/access_log/index.html' for reading
2018-04-15 18:23:59,721 INFO [main] com.hadoop.compression.lzo.GPLNativeCodeLoader: Loaded native gpl library
2018-04-15 18:23:59,724 INFO [main] com.hadoop.compression.lzo.LzoCodec: Successfully loaded & initialized native-lzo library [hadoop-lzo rev 300391394352b074b85b529e870816a72c6f314a]
2018-04-15 18:23:59,730 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2018-04-15 18:23:59,737 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.snappy]
2018-04-15 18:23:59,747 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.ArrayIndexOutOfBoundsException: 1
	at AccessLogMR$TheMapper.map(AccessLogMR.java:46)
	at AccessLogMR$TheMapper.map(AccessLogMR.java:1)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:796)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)
```

**Comment by iShiBin** [comment]
This bug has been reproduced in the sandbox by adding the index.html to the input file.

**Cause**: Exception during tokenizing text in index.html (Not a real data file but exist in the remote S3 buckets)
**Bug**: `if(tokens !=null && tokens.length > 0) {`  
**Fix**: `if(tokens !=null && tokens.length > 1) {`  

The fix has been verified in the sandbox as well.
